# Generated by Django 5.1.5 on 2025-01-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.FloatField()),
                ('max_x', models.FloatField()),
                ('mean_x', models.FloatField()),
                ('median_x', models.FloatField()),
                ('std_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_y', models.FloatField()),
                ('mean_y', models.FloatField()),
                ('median_y', models.FloatField()),
                ('std_y', models.FloatField()),
                ('min_z', models.FloatField()),
                ('max_z', models.FloatField()),
                ('mean_z', models.FloatField()),
                ('median_z', models.FloatField()),
                ('std_z', models.FloatField()),
                ('norm', models.FloatField()),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvprocessor.csvupload')),
            ],
        ),
    ]
